### ISSUE TITLE
Cluster tutorial

### ISSUE THREAD

**Issue by jcsegovia** [adamginsburg/astroquery-paper#17]
We have another tutorial that could be included in the appendix section.

See: http://gea.esac.esa.int/archive-help/tutorials/python_cluster/index.html

**Comment by keflavich** [comment]
@jcsegovia could you add this link, with a 1-sentence description, to Section 4.2 (in a pull request)?

**Comment by jcsegovia** [comment]
Done.

@keflavich the author of this tutorial is Deborah Baines (she is working at ESAC with us). Would it be possible to add her as a co-author...?

**Comment by keflavich** [comment]
Yes, just add her name in the pr, or ask her to submit one

**Comment by keflavich** [comment]
@jcsegovia - could you put that change into a pull request too?
