### ISSUE TITLE
Graceful rendering of empty affil

### ISSUE THREAD

**Issue by pllim** [adamginsburg/astroquery-paper#19]
Right now, (2) is empty line. My LaTeX-fu is too weak to suggest a fix, so I merely open an issue.

![screenshot from 2018-02-15 15-06-29](https://user-images.githubusercontent.com/2090236/36278469-ebbb762a-1261-11e8-9a3d-7a1365c5ea88.png)

**Comment by bsipocz** [comment]
@pllim - I would say not to worry about this now, I'll fix my affiliation before we finish writing up this paper.
