### ISSUE TITLE
Link to stable build of RTD?

### ISSUE THREAD

**Issue by pllim** [adamginsburg/astroquery-paper#21]
I noticed links like http://astroquery.readthedocs.io/en/latest/simbad/simbad.html . Why `latest`? Why not `stable`?

**Comment by bsipocz** [comment]
Given that the services are quite often are moving targets, we tend to link to the latest docs (so it's more likely that it contains already fixed examples) and advise people to use the dev version if they can.

**Comment by pllim** [comment]
Okay. Thanks for the clarification.
