### ISSUE TITLE
Update contribution stats in "The Development Model" section?

### ISSUE THREAD

**Issue by pllim** [adamginsburg/astroquery-paper#23]
Current text:
```
Astroquery has received contributions from 53 people
as of June 2017. While the primary maintenance burden
is shouldered by 2-3 people at any given time, most in-
dividual modules have been implemented independently
by interested volunteers.
```

Any chance an update to the stats can be made to reflect more recent contributions? As of now, June 2017 is already 8 months old.

**Comment by keflavich** [comment]
Yes, we'll update it before publication.  If anyone wants to write a script to do that, it would be welcome...

**Comment by bsipocz** [comment]
I think this number should reflect the latest released version right before submission.

**Comment by pllim** [comment]
Re: Script -- I thought Astropy might have scripts like this. I see a "visualizations_demographics" in `astropy-procedures` but maybe not what you are looking for.

**Comment by bsipocz** [comment]
Oh, indeed, we can use some of the scripts in `astropy-procedures`, e.g `gh_issuereport.py`, also some git shortlog fu detailed in the release procedures.
Though I think we still need to stick to the numbers of a release rather than latest master at the time of update.

**Comment by pllim** [comment]
I see that the number is now from Aug 2018. 🎉
