### ISSUE TITLE
Ensure gallery examples work before paper submission

### ISSUE THREAD

**Issue by pllim** [adamginsburg/astroquery-paper#26]
Since https://astroquery.readthedocs.io/en/latest/gallery.html is explicitly stated under "Online documentation", the referee(s) is bound to try some, if not all, of them.

**Comment by bsipocz** [comment]
I'm opening a sibling issue for this in the main repo. The gallery page is usually very much overseen when doing maintanence, so we may even want to reconsider it's existence?

**Comment by bsipocz** [comment]
oh, we already have that issue open: https://github.com/astropy/astroquery/issues/863

**Comment by bsipocz** [comment]
(I've assigned myself to fix the current examples in case they are failing to work, but I definitely need more input for the adding new examples part of the question).

**Comment by keflavich** [comment]
Solved by https://github.com/astropy/astroquery/pull/1079 ?
