### ISSUE TITLE
A table/appendix listing current supported services?

### ISSUE THREAD

**Issue by pllim** [adamginsburg/astroquery-paper#32]
It is in RTD but would be nice to have in paper?

**Comment by keflavich** [comment]
:+1:.  Volunteers?

**Comment by bsipocz** [comment]
I can do this.

**Comment by eteq** [comment]
I suggested this might go best in Section 2 in #38.  One other thing that came up with some in-person discussions of @keflavich : it would be good to have the legend say something like "this is the list of services at the time of submission, but you should go to <docs link> to see the list as of right now."

**Comment by keflavich** [comment]
Do we / why don't we have a json table (or similar) of supported modules...

**Comment by keflavich** [comment]
We should be able to generate a table based on the entries in `index.rst`, but I'm not sure how best to do that.  Should we scrape our own generated docs?  @eteq?

**Comment by keflavich** [comment]
We're punting this unless we do it by Friday.

**Comment by bsipocz** [comment]
OK, so the referee would like to see this done, too.

```
Section 1, page 2

* List of archives is a collection of acronyms, this is making the assumption that the reader is familiar with all of them. These should be spelt out; alternatively they could be listed in a table.
```

**Comment by keflavich** [comment]
This is now in Table 1.
