### ISSUE TITLE
Mention  supported modules

### ISSUE THREAD

**Issue by bsipocz** [adamginsburg/astroquery-paper#36]
Now that the NASA PDART support has been explicitly mentioned, I feel that we ought to do this for the other similar modules, `mast`, `esasky` and `gaia` come to my mind as other good examples.

**Comment by keflavich** [comment]
Just to clarify, you mean "supported" as in "receives external support", not in the sense used in #32

**Comment by bsipocz** [comment]
Hmm, I'm not sure what @pllim meant in #32, my reading of that was the list for all the modules. While this list is a subset of those that actually has some institutional support behind them rather than volunteering support that we provide.

**Comment by keflavich** [comment]
Yes, OK, we read these in the same way.  I was just highlighting the fact that 'support' is ambiguous without the additional clarifying text.

**Comment by pllim** [comment]
I apologize for the confusion. In #32, I simply meant a list of modules, not who is paying for what.

**Comment by keflavich** [comment]
These references are now included.
