### ISSUE TITLE
additional API examples in appendix?

### ISSUE THREAD

**Issue by mommermi** [adamginsburg/astroquery-paper#37]
I was wondering if we should more examples to the appendix. It's probably overkill to provide examples for each module, but maybe we should provide short examples for modules that use different APIs? Modules that use the same API as a specific example can be pointed out in the example description.

**Comment by keflavich** [comment]
I would be happy to have those.  Please contribute if you think of one!  

However, we don't want to treat this as a tutorial paper; we should limit the examples to things with different APIs or different astroquery capabilities.  So, for example, we might have one example for a generic get-a-catalog query, another for a get-an-image query, and maybe a third if there are any tricky one-off cases.... I can't think of any immediately, though, except for the various delayed-archive-query types that are not common across different modules and therefore do not belong in the paper.

**Comment by bsipocz** [comment]
I feel somewhat ambivalent with the examples. 

It's good to have them in the paper, but we have to be careful as they also quickly became obsolete. For this reason we didn't have examples in the new astropy paper and rather point to the documentation where appropriate. I feel doing the same (with the exception of point out some generic API design concepts) with astroquery would be extremely difficult but not impossible, so this is just some food for thoughts.

**Comment by mommermi** [comment]
@bsipocz makes a good point. We could simply explain this standpoint and refer to the documentation in the appendix.
