### ISSUE TITLE
Section 2.1: About continuous deployment

### ISSUE THREAD

**Issue by pllim** [adamginsburg/astroquery-paper#43]
One question about continuous deployment -- Is there a way to opt out of deployment when a PR is merged? Say, you merge Part 1 but don't wanna deploy until Part 2 is merged in a separate PR. If there is a way to do it, perhaps should mention in paper?

**Comment by keflavich** [comment]
I don't think this belongs in the paper, and at the moment, we can't do it.   Any ideas how we would implement this?

**Comment by pllim** [comment]
Didn't @bsipocz suggested some kind of `[skip deploy]` commit message hook or something?

Anyway, if it does not belong here, feel free to move or close. Thanks for the swift response!

**Comment by keflavich** [comment]
Moved to astropy/astroquery

**Comment by bsipocz** [comment]
I think the exact details are irrelevant to the paper as only people being able to push to master have the power to control the deployment.

By the magic word is `[nodeploy]` in the commit message directly on master (so practically in the merge commit message).
