### ISSUE TITLE
Appendix A: Code presentation

### ISSUE THREAD

**Issue by pllim** [adamginsburg/astroquery-paper#48]
Perhaps the ship has sailed or simply impossible given page limits etc, but I am wondering if Jupyter notebook would render the example nicer.

**Comment by keflavich** [comment]
I prefer non-notebook demos personally

**Comment by pllim** [comment]
OK feel free to close if you want. I was just thinking aloud.

**Comment by keflavich** [comment]
If you want to implement a prettier version, I won't object, but I don't think it's needed.
