### ISSUE TITLE
Authors in ApJ-format?

### ISSUE THREAD

**Issue by keflavich** [adamginsburg/astroquery-paper#51]
ApJ wants the author list uploaded in this format:

https://aas.msubmit.net/html/Authors_Template.xls

Anyone want to convert our list into that format?  I don't know how it works since there's no column for an ORCID and the manual form has such an entry.  It would be nice if we could extract this metadata automatically from the latex...

**Comment by pllim** [comment]
I have an idea: ~~Astropy Table~~ (nope) -> Format it for XLS -> pandas -> to_excel

Let me see. No promises.

**Comment by keflavich** [comment]
yeah, the tricky thing is loading the authors into any usable table format.  I feel like ADS tools should support this...

**Comment by pllim** [comment]
I think I am close... See #52
