### ISSUE TITLE
Adding acknowlegment section

### ISSUE THREAD

**Issue by bsipocz** [adamginsburg/astroquery-paper#55]

**Comment by bsipocz** [comment]
I'll add the first draft of this tomorrow night.

**Comment by keflavich** [comment]
Bump!

**Comment by bsipocz** [comment]
I've started it, and will finish this (and the rest) the second half of this week.

**Comment by keflavich** [comment]
This is solved in #62, though it's not labeled "acknowledgements"

**Comment by keflavich** [comment]
(that's a latex issue though)
