### ISSUE TITLE
Add a software section

### ISSUE THREAD

**Issue by keflavich** [adamginsburg/astroquery-paper#60]
should include:

requests
beautifulsoup
keyring
astropy

what else?

**Comment by pllim** [comment]
Does this cover everything? https://github.com/astropy/astroquery/blob/master/pip-requirements

**Comment by keflavich** [comment]
yeah, I guess?  Maybe there's more...?

**Comment by bsipocz** [comment]
This is a flight hack, so I'm trying to get it done tomorrow night.

**Comment by keflavich** [comment]
```
numpy
astropy
requests
keyring
beautifulsoup4
html5lib
```

**Comment by keflavich** [comment]
Added in PR #62
